### ISSUE TITLE
Update the docker configuration

### ISSUE THREAD

**Issue by jessehartloff** [makeopensource/devU#114]
### Subject of the issue
-------------------------------------------
Running docker compose up from a fresh clone is currently broken with a missing package-lock.json file and several front end TS errors. 

### Expected behavior
-------------------------------------------
The app should run and be accessible via a browser after only cloning and running docker compose up

### Actual behavior
-------------------------------------------
Errors while building the docker containers

### Steps to reproduce
-------------------------------------------
Clone. Docker compose up.

### Any relevant logs, error output, etc?
-------------------------------------------
=> ERROR [client stage-1 3/7] COPY ./devU-client/package.json ./devU-client/package-lock.json ./

**Comment by SantarinX** [comment]
I believe the error was caused by my removal of package-lock.json, which was discussed in the meeting before, took way too long to copy package-lock.json into docker image.  remove the ./devU-client/package-lock.json in client.dockerfile and api.dockerfile will pass this error.

By the way, do not forget to also clone the submodule by `git submodule update --init --recursive` if first time clone
